### ISSUE TITLE
Story: Do a POC of the Jenkins4coco container idea

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#29]
We need a plain Jenkins master LTS version, as a container, but with one addition - the jenkins configuration-as-code plugin installed.

The container needs to accept an environment variable on start, where we point the configuration file for the plugin (the YML file).

The "pointer" to configuration could be to a git repository, a gist or a local directory available upon start of the container.

The plugin can be installed using hpi-file from this repository, but the container needs to be released.

For now also the Dockerfile for this container can live here in this repo.

Groom this issue to workable issues.

The goal of this work is to make it easy to use this hole complete setup, which is one of the improvements we're working to achieve with jenkins configuration as code.

**Comment by groenborg** [comment]
This issue is a story and we can break it down to three issues. 
First we need a Dockerfile based on the official Jenkins LTS with a job that builds the casc hpi and add it to the work folder.
The next is to fetch and add a configuration through an env-variable which points to a file on GitHub. 
The third issue is automating this. We need a setup that automatically builds our plugin and creates a new docker image, available on docker hub

**Comment by buep** [comment]
Broken down by @groenborg to these issues:

* #52 
* #54 
* #53

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.

there will be an image
