### ISSUE TITLE
add our own simple plugin implementation

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#42]
If we can write our own simple plugin, and make it available through the xml file we can easily deduct how the parser works, and maybe figure out what is necessary for the plugin to run

http://code.hootsuite.com/how-to-write-a-jenkins-plugin/

**Comment by buep** [comment]
For it to really work, we would need to publish it also... which might be scope creep for now?
Or could we install it otherwise?

Another thing is if we are going down this path of having a "demo" plugin showing how our setup work, it should also be the plugin to check when looking at best-practices on Jenkins implementation of plugins... like, this is the way to use symbols, this is how extensions should be used, this is how databound contructors are good.... 

That plugin could be quite valuable... maybe also to the community.
But again it is pretty much work for now I think....

**Comment by groenborg** [comment]
the guide in the link creates a __very__ basic plugin, but I think they show best practice.. So for us to spend a small amount of time creating a plugin with all the learnings could clear up a few things
1. What interfaces a required to implement
2. what annotations are required
3. get a grip on jelly

**Comment by groenborg** [comment]
installation does not matter.. I learned from Fridays that a `clean package was not required to regenerate the docs`

**Comment by buep** [comment]
We will not be working on this right now - might be good for later, so we keep it as a briefing.

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
