### ISSUE TITLE
Support for `plugin.yml` to install plugins

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#44]
When I as a Jenkins administrator want to install a plugin, I will add a line to the `plugin.yml` file with the name of the plugin (artifact name) and the version.

This will have to correspond to exactly the name and version I would tick in the Jenkins Manage Plugin UI and I will expect all dependencies are pulled in as well.

For example I will only mention 

`git 3.6.3` to install the _Git Plugin_ in version 3.6.3.

See issue #45  for support of un-installing plugins and other useful features we might implement later.

**Comment by kryptag** [comment]
Closing this issue because of the estimate has overrun.

# Findings:
Got it to install a plugin with a hardcoded value in this instance i used `workflow-aggregator` which is the pipeline plugin.

There is a problem with adding versions, so right now we get the latest version.

Handling dependencies isn't a problem because Jenkins will resolve this for us and install the needed dependencies.

I moved the hardcoded value out of the method and created a new file `plugin.yml` and then loaded the plugin names into a list which i pass to `pluginManager.install(Collection<String>, Bool)` this caused an error `hudson.model.Failure: No such plugin: workflow-aggregator`.

# Conclusion:
Because of the overrun on this issue i have to add the changes made and i will open up 2 new issues  regarding `hudson.model.Failure: No such plugin: workflow-aggregator` and adding version for plugins.
