### ISSUE TITLE
Resolve Plugins not being found 

### ISSUE THREAD

**Issue by kryptag** [Praqma/configuration-as-code-plugin#48]
when running `Jenkins.getInstance().pluginManager.install(Collection<String, Bool)`with a List of strings we get `hudson.model.Failure: No such plugin: workflow-aggregator`. So for some reason we can't find the plugin we want. I experienced this earlier in the process and i have an idea that it can be because we execute `InstallPlugins()` to early, but this is only a hypothesis

Spawned from: #44

**Comment by buep** [comment]
Oh, yes.... if you look at Jenkins just after start-up the plugin list is empty, because it haven't looked at update center yet.

So continue to look into this with that as the failure. See if you can check somwhere in Jenkins when latest update center update happened, and it is isn't done yet then trigger it.

Timebox it.
