### ISSUE TITLE
Jenkins job to build  JCasC docker image

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#54]
Create Jenkins job to make a new image of our build

**Comment by buep** [comment]
Build steps:

* mvn package to get an hpi file
* docker build on Dockerfile that will copy in that hpi file into jenkins plugin folder so Jenkins start with the plugin loaded

**Comment by ewelinawilkosz2** [comment]
job to be created at our https://jenkins.praqma.cloud/
jobDSL to be used 
I removed "push do docker hub" part since this will wait until we're happy with the image

**Comment by ewelinawilkosz2** [comment]
Dockerfile is ready - #58, Jenkinsfile & Jenkinsfile.dsl are part of this repository, https://jenkins.praqma.cloud/ contains now seedjob for creating those. The issue now is that utility slave I wanted to use to build our docker need to have docker version updated :) I get:
Error parsing reference: "maven:3.5-jdk-8-slim as builder" is not a valid repository/tag
and according to https://github.com/arun-gupta/docker-java-multistage/issues/1 new docker is required. I will check with @mortench3000 if we can do something about it

**Comment by ewelinawilkosz2** [comment]
I upgraded docker version on host machine: https://github.com/Praqma/noops/issues/340
I don't really understand what is happening, because I run it on slave with another docker version installed.. but well, the build is successful now:
https://jenkins.praqma.cloud/job/configuration-as-code-plugin/

we can start thinking about putting it in dockerhub
