### ISSUE TITLE
Create demonstration docs - examples of plugins working and not (and why not)

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#59]
To later be used for input for testing as well.

**Comment by buep** [comment]
A white list kind of, link to demo.

Enable the community to contribute to this list.

**Comment by ewelinawilkosz2** [comment]
@groenborg I think you should close this one, instead of #61 - when we implement we do not take the ones we call "story" but issues mentioned in story. I understand it might not be clear enough :) just please confirm this is what you pushed in https://github.com/Praqma/configuration-as-code-plugin/commit/21c43cce219ff16c2f419394d56dca0cfd33e03e and close
@buep please confirm that I got your "story" idea right and reopen #61 if you think we still need the story

**Comment by groenborg** [comment]
Yes that is right. I will close this one
